# Project-specific AEM configuration

# Inherit default AEM functionality from "AEM Definitions", see http://devops.wcm.io/conga/definitions/aem/
inherits:
- role: aem-cms

variants:
- variant: aem-author
- variant: aem-publish

templateDir: wcmio-aem-archetype-aem-cms

files:


# AEM OSGi System Configuration
- file: wcmio-aem-archetype-aem-cms-config.provisioning
  dir: packages
  template: wcmio-aem-archetype-aem-cms-config.provisioning.hbs
  postProcessors:
  - aem-contentpackage-osgiconfig
  postProcessorOptions:
    contentPackage:
      name: wcmio-aem-archetype-aem-cms-config
      rootPath: /apps/wcmio-aem-archetype/config
      filters:
      - filter: /apps/wcmio-aem-archetype
        rules:
        - rule: include
          pattern: /apps/wcmio-aem-archetype/config(\..*)?(/.*)?
        - rule: exclude
          pattern: /apps/wcmio-aem-archetype/config/rewriter(/.*)?

# Include URL handler in Sling Rewriter configuration
- file: wcmio-aem-archetype-aem-cms-rewriter-config.json
  dir: packages
  template: wcmio-aem-archetype-aem-cms-rewriter-config.json.hbs
  validatorOptions:
    contentPackage.validatorsSettings:
      jackrabbit-filter:
        options:
          validRoots: /apps/wcmio-aem-archetype/config
  postProcessors:
  - aem-contentpackage
  postProcessorOptions:
    contentPackage:
      name: wcmio-aem-archetype-aem-cms-rewriter-config
      packageType: application
      rootPath: /apps/wcmio-aem-archetype/config/rewriter

# wcm.io
- url: mvn:io.wcm/io.wcm.caconfig.editor//zip/content
  dir: packages
- url: mvn:io.wcm/io.wcm.handler.url//zip/content
  dir: packages
- url: mvn:io.wcm/io.wcm.handler.link//zip/content
  dir: packages
- url: mvn:io.wcm/io.wcm.handler.media//zip/content
  dir: packages
- url: mvn:io.wcm/io.wcm.handler.richtext//zip/content
  dir: packages
- url: mvn:io.wcm/io.wcm.wcm.commons//zip/content
  dir: packages
- url: mvn:io.wcm/io.wcm.wcm.core.components//zip/content
  dir: packages
- url: mvn:io.wcm/io.wcm.wcm.parsys//zip/content
  dir: packages
- url: mvn:io.wcm/io.wcm.wcm.ui.granite//zip/content
  dir: packages
- url: mvn:io.wcm/io.wcm.wcm.ui.clientlibs//zip/content
  dir: packages

# Application package
- url: mvn:io.wcm.devops.conga.plugins.aem.it/io.wcm.devops.conga.plugins.aem.it.aemsample.complete//zip
  dir: packages

# Application conf content package
- url: mvn:io.wcm.devops.conga.plugins.aem.it/io.wcm.devops.conga.plugins.aem.it.aemsample.conf-content//zip
  dir: packages
  condition: ${app.confContent}

# Application sample content package
- url: mvn:io.wcm.devops.conga.plugins.aem.it/io.wcm.devops.conga.plugins.aem.it.aemsample.sample-content//zip
  dir: packages
  condition: ${app.sampleContent}


# Defines configuration parameters and default values
config:
  contentPackage:
    group: it
    version: ${version}

  app:
    confContent: true
    sampleContent: false

  # Log levels
  log:
    projectSpecificLogLevel: warn
