templateDir: aem

files:

# Define a AEM content package containing OSGi configurations from a Sling Provisioning file
- file: sling-provisioning.provisioning
  dir: packages
  template: sling-provisioning.provisioning.hbs
  # Transform OSGi configs from provisoning file to AEM content package
  postProcessors:
  - aem-contentpackage-osgiconfig
  postProcessorOptions:
    contentPackage:
      name: config-sample
      description: The description of the sample package.
      version: "${version}"
      rootPath: /apps/sample/config
      filters:
      - filter: /apps/sample


# Define a AEM content package with some JCR content (Sling Mapping Example)
- file: sling-mapping.json
  dir: packages
  template: sling-mapping.json.hbs
  # Transform JSON file to AEM content package
  postProcessors:
  - aem-contentpackage
  postProcessorOptions:
    contentPackage:
      name: mapping-sample
      rootPath: /etc/map/http
      filters:
      - filter: /etc/map/http
        rules:
        - rule: exclude
          pattern: /etc/map/http
        - rule: include
          pattern: /etc/map/http/.*
        - rule: exclude
          pattern: /etc/map/http/AppMeasurementBridge

# AEM Systems users with ACLs
- file: aem-systemusers.json
  dir: packages
  template: aem-systemusers.json.hbs
  # Transform JSON file to AEM content package
  postProcessors:
  - aem-contentpackage
  postProcessorOptions:
    contentPackage:
      name: aem-systemusers
      acHandling: merge
      rootPath: /
      filters:
      - filter: /content/rep:policy
      - filter: /home/users/system/sample/sampleSystemUser

# AEM Replication (Author)
- file: aem-replicationagents.json
  dir: packages
  template: aem-replicationagents.json.hbs
  postProcessors:
  - aem-contentpackage
  postProcessorOptions:
    contentPackage:
      name: aem-cms-author-replicationagents
      rootPath: /etc/replication
      filters:
      - filter: /etc/replication/agents.author

# Download AEM content package and extract properties
- url: mvn:io.wcm/io.wcm.caconfig.editor.package//zip
  dir: packages


# Defines configuration parameters and default values
config:

  contentPackage:
    group: sample
    version: "${version}"
    thumbnailImage: classpath:/wcm-io-package-thumbnail.png

  jvm:
    path: /path/to/java
    heapspace:
      min: 512m
      max: 2048m
    permgenspace:
      max: 256m

  replication:
    author:
      publishTargets:
      #- name: publish1
      #  url: http://localhost:4503
      #  transportUser: admin
      #  transportPassword: admin

  var1: Value 1
